version: '2'
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:5.7
    tty: true 
    restart: unless-stopped 
    environment:
      - MYSQL_DATABASE=Escrito
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    ports:
        - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
